[project]
name = "hterm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pyside6>=6.10.1",
    "qtpy>=2.4.3",
    "ymodem",
]

[tool.uv.sources]
ymodem = { git = "https://github.com/o-murphy/ymodem.git" }
